services:
  postgres:
    image: postgres:16-alpine
    container_name: bolao_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bolao
      POSTGRES_PASSWORD: bolao123
      POSTGRES_DB: bolao_copa
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres
        -c timezone=America/Sao_Paulo
        -c log_timezone=America/Sao_Paulo

volumes:
  postgres_data: